### ISSUE TITLE
PopupFeature Hide Collaspe Button 

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#1091]
![image](https://github.com/user-attachments/assets/1b91201a-0a3a-49e2-80af-b36bb3587450)

hi, i need some help to know whether am i able to disable the button in red box

**Comment by Viglino** [comment]
You can style it using CSS:
```CSS
/* hide fix */
.ol-popup-content .ol-fix {
  display: none;
}
```
or just disabled
```CSS
/* disable fix */
.ol-popup-content .ol-fix {
  pointer-events: none;
  opacity: 0.5;
}
```
