### ISSUE TITLE
Print Dialog Responsive on Mobile Devices

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#1095]
How can the print parameters settings panel (Left panel) be collapsed/expanded (Responsive) when on mobile devices?

<img width="390" alt="image" src="https://github.com/user-attachments/assets/807a3d78-4aee-4391-a053-51cfa24261ea">

**Comment by Viglino** [comment]
You can use CSS and and media query to make it more responsible.
The current CSS only change the width of the panel:
```CSS
@media (max-width: 25em) {
    .ol-ext-print-dialog .ol-print-param {
        width: 13em;
    }
}
@media (max-width: 25em) {
    .ol-ext-print-dialog .ol-print-map {
        width: calc(100% - 13em);
    }
}
```
You can add a button to toggle the panel using getUserElement (or getContentElement):
```javascript
var bt = document.createElement('BUTTON')
bt.innerText = 'ok'
printControl.getUserElement().appendChild(bt)
```
