### ISSUE TITLE
Checkbox layer Group

### ISSUE THREAD

**Issue by Ballantines42** [Viglino/ol-ext#145]
Hello,

I want to delete a checkbox before Layer Group Name, it's possible?

Thanks for your help

**Comment by Viglino** [comment]
You can use the css to change the check box on group layers in the list (`.ol-layerswitcher li.ol-layer-group`) and prevent click using `pointer-event:none` on the label. But this will be for all the group layers.

If you want to handle layers individually in the list you can listen to the `drawlist ` event and change the behaviour of the element:
````javascript
switcher.on('drawlist', function(e){
  // The layer 
  var layer = e.layer;
  // The list element
  var elt = e.li;
  // Do something with the element
  if (e.layer===myLayer) {
    // Remove the input
    $('input', e.li).remove();
  }
});
````

@+

**Comment by Ballantines42** [comment]
Thanks for your help but

**Comment by Ballantines42** [comment]
Thanks for your help but i think we misunderstood each other...
I want delete checkbox red no checkbox blue...
![image](https://user-images.githubusercontent.com/27500104/43717311-6ab6d53a-9987-11e8-8321-2ebf2924fa7c.png)

**Comment by Viglino** [comment]
I'm speaking about this [layerswitcher](http://viglino.github.io/ol-ext/examples/control/map.switcher.html) which is part of the lib.

**Comment by Ballantines42** [comment]
I use this , i have just modified CSS

**Comment by Viglino** [comment]
OK, let's see that https://codepen.io/viglino/pen/ZjMYyJ

With css:
````css
/* remove the check */
#map .ol-layer-group > .li-content label:after,
#map .ol-layer-group > .li-content label:before {
  content:unset;
}
/* Prevent clic */
#map .ol-layer-group > .li-content label {
  padding-left: .5em;
  pointer-events: none;
}
````
