### ISSUE TITLE
Editbar customization

### ISSUE THREAD

**Issue by Dkkemaries** [Viglino/ol-ext#235]
Hello, 

I found the current EditBar (http://viglino.github.io/ol-ext/examples/bar/map.control.editbar.html) very useful , but in my case I don't need Offset,Split ,Delete functions . Is it possible to disable them , something like editbar.remove('Offset')  or I need to create my own toolbar ? 

Is it possible to combine/extend edit bar with my own buttons/functions?

BR,

**Comment by ThomasG77** [comment]
You just need to change

```javascript
var edit = new ol.control.EditBar({ source: vector.getSource() });
```

with

```javascript
var edit = new ol.control.EditBar({ source: vector.getSource() , interactions: {
  Offset: false,
  Split: false,
  Delete: false
}});
```
PS: @Viglino I was able to find out the info through https://github.com/Viglino/ol-ext/blob/69c0b540ebb2b4a0e99fc77da7ce8def37325a4a/src/control/EditBar.js#L25 but it seems the API docs is not up to date as I don't find EditBar in the API documentation

**Comment by Dkkemaries** [comment]
Thanks

**Comment by Viglino** [comment]
@ThomasG77 Yes the doc has to be rebuild to reflect the code content...
I've also add the positionality to give an custom interaction to the control:
````javascript
var edit = new ol.control.EditBar({ source: vector.getSource() , interactions: {
  Select: new ol.interaction.Select()
}});
````
This can be useful to customize the interaction (set multi selection, set style on the interaction, etc.)
A boolean true/fallse can be used to use the default interaction or to remove the interaction from the bar.
@+

**Comment by Dkkemaries** [comment]
Is it possible to remove UndoDraw/FinishDraw and their associated buttons in same manner ?

**Comment by Viglino** [comment]
You can remove the sub bar using css:
````css
/* remove all option bars for our map */
#map .ol-option-bar {
  display: none;
}
````
````css
/* remove draw polygon option bar for our map */
#map .ol-control.ol-bar .ol-control .ol-bar {
  display: none;
}
````
