### ISSUE TITLE
Customize layerswitcher icon

### ISSUE THREAD

**Issue by pmabey** [Viglino/ol-ext#283]
Is it possible to change the layerswitcher icon so that is looks similar to the other icons used in the control bar for example? It looks like its possible by customizing the CSS but it seems lots of things need to be changed to make that happen. Alternatively, adding the layerswitcher button to the control bar would be really nice as I am trying to find a way to better organize the various control buttons I have on my map.

**Comment by Viglino** [comment]
The button in the layerswitcher is just one style with a :before and :after. it is a little bigger than the other one and has a blank background.
Try this to make it looks link others
````css
.ol-control.ol-bar .ol-control button {
    font-size: 1.14em;
    background-color: rgba(0,60,136,.5);
}
````
You can't place the layer switcher in a bar as it needs its own div to display the layer list.
You can place the layerswitcher in an overlay (http://viglino.github.io/ol-ext/examples/control/map.control.overlay.menu.html) and add a standard button to a bar to open the overlay...
