### ISSUE TITLE
GeoBookmark

### ISSUE THREAD

**Issue by arszp10** [Viglino/ol-ext#338]
I ran into a problem in below image

![image](https://user-images.githubusercontent.com/12972343/63420364-3092ee80-c40f-11e9-8d74-95dbf6cffc3a.png)

I think I need to add the following features [GeoBookmark](https://github.com/Viglino/ol-ext/blob/253c3d4774e00761221d868bf21443dda3f49872/src/control/GeoBookmark.js#L25):

- search
- drag
- rename
- scroll if not fit

**Comment by Viglino** [comment]
Hello,

It could be interesting. Drgging is a bit tricky...
Adding sub-menu could be also a good behavior.

To add scrolling:
````css
.ol-control.ol-bookmark {
    max-height: calc(100% - 2em);
    overflow: auto;
}
````
