### ISSUE TITLE
map.control.overlay.menu example, doesn't seem to work properly with latest version of Font Awesome

### ISSUE THREAD

**Issue by MarByteBeep** [Viglino/ol-ext#523]
In the example `map.control.overlay.menu.html` try replacing the font awesome css:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
```
with the latest version of Font Awesome:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
```

And observe that the the bars glyph (`\f0c9`) is not drawn. The Font-Family name had changed since 4.7.0, from `FontAwesome` to `Font Awesome 5 Free`. So I changed that too:

```css
.ol-overlay.menu .ol-closebox:before
{	content:"\f0c9";
	font-family: "Font Awesome 5 Free";
}
```

But still that specific glyph isn't drawn. In Firefox it appears as a missing glyph; in Chrome it is drawn as an empty character.

Drawing that glyph anywhere else on the menu, works fine. It only doesn't seem to work with that close button. So I'm suspecting some JS code is interfering here, or am I missing something? 

Thanks!

**Comment by Viglino** [comment]
Are you sure the style is not overridden by an other one ? 
Try to force the font-family:
```css
font-family: "Font Awesome 5 Free"!important;
```
There is no js code to display an element, this is handled by the css...

**Comment by MarByteBeep** [comment]
Thanks for the reply! No, adding `!important` unfortunately resulted in the same issue. I really don't understand what's going on here. It's a big css mystery :)

**Comment by Viglino** [comment]
Do you have an example online?

**Comment by MarByteBeep** [comment]
Yes, just take the `map.control.overlay.menu.html` example that is bundled and replace this line:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
```

with the latest version of Font Awesome:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
```

That should show you the problem

**Comment by Viglino** [comment]
You have to add the font-weight to get it run...
```css
.ol-overlay.menu .ol-closebox:before {
    content: "\f0c9";
    font-family: "Font Awesome 5 Free";
    font-weight: 900;
}
```
