### ISSUE TITLE
map.control.overlay.menu: possible to resize height based on actual content?

### ISSUE THREAD

**Issue by MarByteBeep** [Viglino/ol-ext#527]
In the current example of `map.control.overlay.menu` the menu uses a height of 100%: it runs from the top to the bottom. 

See:
http://viglino.github.io/ol-ext/examples/control/map.control.overlay.menu.html

Is it possible to have this menu resize its height so that it fits the content? The problem is that my menu can have dynamic content, so a fixed height doesn't work. And 100% is just too tall.

**Comment by Viglino** [comment]
It's just css options, you can use your own declaration to let the menu resize as you want in your CSS...
```CSS
#map .ol-overlay.menu {
    height: auto;
    bottom: auto;
    max-height: 100%;
}
```
