### ISSUE TITLE
Expand Collapse buttons to the left of checkbox in layer control

### ISSUE THREAD

**Issue by 1Map** [Viglino/ol-ext#706]
How can I move the layer group expand/collapse buttons to be on the left of the checkbox?

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1152458/144233173-7ef5653c-752b-4ae4-b7a3-8d66dce8932b.png">

**Comment by Viglino** [comment]
Just use CSS:
```CSS
.ol-layerswitcher .panel li.ol-layer-group > .ol-layerswitcher-buttons {
  position: absolute;
  width: 100%;
}
.ol-layer-group > .li-content {
  left: 1.5em;
}
.ol-layerswitcher .expend-layers, .ol-layerswitcher .collapse-layers {
  float: left;
}
```
Or use `drawlist` event to ad your own button...
