### ISSUE TITLE
LayerPopup: Disable Highlighting of current selection?

### ISSUE THREAD

**Issue by Siedlerchr** [Viglino/ol-ext#726]
This time it's not a typing issue ;)
I am using a LayerPopup for controlling the visibility of layers. 
When I click/tap on a selected layer to hide it, it still has the highlighting color because it's selected. This makes it looks like it would be still active. 
That's a bit confusing. Is there a way to disable the highlighting? I couldn't find an option.  Would  be cool to have this!
Thanks in advance!

**Comment by Viglino** [comment]
The highlight is controlled by CSS, you have to add in your CSS:
```CSS
.ol-layerswitcher-popup li:hover {
  background: #fff;
  color:#369;
}
.ol-layerswitcher-popup li.ol-visible:hover {
  background:rgba(0, 60, 136, 0.7);
  color:#fff;
}
```
