### ISSUE TITLE
How can i Change Position of print icon and layer switcher ? i am trying to put all control at one place 

### ISSUE THREAD

**Issue by psujjainkar** [Viglino/ol-ext#745]
![Screenshot 2022-02-25 144652](https://user-images.githubusercontent.com/16004804/155688074-2d355496-318a-4408-88d5-49f84a2b0aa0.png)
![Screenshot 2022-02-25 144722](https://user-images.githubusercontent.com/16004804/155688081-29f18531-f778-4da6-b8d7-e82ecda2b3cf.png)

**Comment by Viglino** [comment]
Use CSS
```CSS
.ol-control.ol-print {
    top: 0.5em;
    left: 3em;
}
.ol-control.ol-layerswitcher {
    right: 0.5em;
    top: 3em;
}
```
