### ISSUE TITLE
How to open ol.control.LayerPopup via ol.control.Button

### ISSUE THREAD

**Issue by thn80** [Viglino/ol-ext#787]
Hi,
is it possible to open an ol.control.LayerPopup via a click on a ol.control.Button?
What I want to achieve is: I don't like the "Layers" button style on the map in the example https://viglino.github.io/ol-ext/examples/control/map.switcher.popup.html and, therefore, I want to exchange it to have a button like in the example https://viglino.github.io/ol-ext/examples/bar/map.control.button.html. Is this possible? Could someone give me a hint?
Currently, my understanding is that I need to use the "element" propertie of the ol/control/Control, but I don't know how to assign a Control Button to it. Or is there a better approach?
Thanks.

**Comment by Viglino** [comment]
If you want to place the layer panel in a specific target you can use the `target` option. This option lets you choice the place you want to set the layer list (without button). But you have to handle it differently (see https://codepen.io/viglino/pen/vxGOQN).

If you want to customize the button itself, just use css (see here https://viglino.github.io/ol-ext/examples/control/map.switcher2.html)
The main issue is that the default css use `:before` and `:after` you have to reset... (see https://codepen.io/viglino/pen/abqGMjJ)
```CSS
/* Reset CSS */
.ol-layerswitcher.mySwitcher > button {
  font-size: 1em;
  background-color: rgba(0,60,136,.5);
} 
.ol-layerswitcher.mySwitcher > button:before, 
.ol-layerswitcher.mySwitcher > button:after {
  all: unset;
}
/* Your own button */
.ol-layerswitcher.mySwitcher > button:before {
  content: 'A'
}
```
