### ISSUE TITLE
ol-ext: Search

### ISSUE THREAD

**Issue by ngjiajunsg** [Viglino/ol-ext#802]
can i ask for search feature can i auto display the search textbox instead of click the icon to display the textbox

**Comment by Viglino** [comment]
Just use CSS:
```CSS
.ol-search input {
  display: inline-block!important;
}
```
