### ISSUE TITLE
Control Bar Position Top

### ISSUE THREAD

**Issue by thn80** [Viglino/ol-ext#812]
Hi,

I'm trying to place my control bar to the very top (~0.5em). However, even if configuring "top: 0em;" there is a bigger distance between the control bar and the top of the map. For me it seems, that - maybe - the zoom controls (+/-) cause the control bar to be placed after them.

<img width="337" alt="control_bar_top" src="https://user-images.githubusercontent.com/2078784/177037777-b7a90596-f9e5-44ce-8467-a92c49cd5b3f.png">

Could someone give me a hint on how to place the control bar to the very top?

Thanks in advance

**Comment by Viglino** [comment]
Just use CSS to style the control:
```CSS
.ol-control.ol-bar.ol-top.ol-right {
    top: 0;
}
```

**Comment by thn80** [comment]
This worked for me (at least for the browsers Firefox and Chrome on Windows). However, when accessing the page with Chrome on Android, the problem still seems to be there.
Any ideas?

<img width="534" alt="ol-ext_windows_firefox" src="https://user-images.githubusercontent.com/2078784/177203035-ded7b616-bb48-4cb6-b3af-7ce0b09aa1bc.png">

![ol-ext_android_chrome](https://user-images.githubusercontent.com/2078784/177203044-17e92b04-90ef-41d7-ad83-efe65a5b8985.jpg)

**Comment by Viglino** [comment]
On smartphone (touch devices) buttons are bigger and thus position must be define.
Just add `.ol-touch` class to the css:
```css
.ol-touch .ol-control.ol-bar.ol-top.ol-right,
.ol-control.ol-bar.ol-top.ol-right {
    top: 0;
}
```
