### ISSUE TITLE
Popup Feature - move title when count is present

### ISSUE THREAD

**Issue by andreaordonselli** [Viglino/ol-ext#972]
In the popupfeature I moved the count to the top left in the case of `.ol-popup-top.ol-popup-left`, how can I move the title further to the right only if the count is present?

the problem is: h1 element is before ol-count div

for now i used css with `has` but it is not supported by all browsers

```css
/* select all h1 elements preceding .ol-count */
.ol-popup-top.ol-popup-left .ol-popup-content .ol-popupfeature h1:has( ~ .ol-count) {
padding-left: 56px;
}
```
